version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ez-casino-api
hook:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/applications_start.sh
      timeout: 300
      runas: ec2-user
