exports.statusType = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  FOR_APPROVAL: "FOR_APPROVAL",
  REJECT: "REJECT",
  DELETED: "DELETED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  ONGOING: "ONGOING",
});

exports.userTypes = Object.freeze({
  AGENT: "AGENT",
  SUPER_USER: "SUPER_USER",
  CLUB_ADMIN: "CLUB_ADMIN",
});
